'use client'

import { useEffect, useState, useCallback, useMemo } from 'react'
import { toast } from 'sonner'

// ══════════════════════════════════════════════════════════
// ══ TYPES ══
// ══════════════════════════════════════════════════════════

type PoseId =
  | 'blank' | 'coding' | 'search' | 'bling' | 'building'
  | 'reading' | 'heart' | 'ecosystem' | 'question' | 'sweating'
  | 'coffee' | 'door' | 'meme' | 'heroLaptop'
  | 'dejected' | 'sparkle' | 'smoking' | 'sleepy' | 'eating' | 'wink'
  | 'coin'

type PoseAlias = 'main' | 'loading' | 'notfound' | 'empty' | 'success'
  | 'careers' | 'investors' | 'companies' | 'articles' | 'bookmarks' | 'error' | 'login'

interface PixelbaraProps {
  pose: PoseId | PoseAlias
  size?: number
  className?: string
  clickable?: boolean
  suppressHover?: boolean
}

// ══════════════════════════════════════════════════════════
// ══ HOOKS ══
// ══════════════════════════════════════════════════════════

function useIsDark() {
  const [dark, setDark] = useState(false)
  useEffect(() => {
    setDark(document.documentElement.classList.contains('dark'))
    const obs = new MutationObserver(() =>
      setDark(document.documentElement.classList.contains('dark'))
    )
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] })
    return () => obs.disconnect()
  }, [])
  return dark
}

type TimeOfDay = 'dawn' | 'morning' | 'lunch' | 'afternoon' | 'evening' | 'night'

function useTimeOfDay(): TimeOfDay {
  const [time, setTime] = useState<TimeOfDay>('morning')
  useEffect(() => {
    const check = () => {
      const h = new Date().getHours()
      if (h >= 0 && h < 6) setTime('dawn')
      else if (h < 11) setTime('morning')
      else if (h < 13) setTime('lunch')
      else if (h < 18) setTime('afternoon')
      else if (h < 21) setTime('evening')
      else setTime('night')
    }
    check()
    const id = setInterval(check, 60000)
    return () => clearInterval(id)
  }, [])
  return time
}

// ══════════════════════════════════════════════════════════
// ══ COLOR PALETTE - HIGH RESOLUTION CAPYBARA ══
// ══════════════════════════════════════════════════════════

const P: Record<string, [string, string]> = {
  // Fur - warm brown tones
  F: ['#C4956A', '#D4A57A'],   // Main fur - warm caramel
  f: ['#A67B52', '#B88B62'],   // Shadow fur - darker
  d: ['#8A6542', '#9A7552'],   // Deep shadow
  u: ['#D8A878', '#E8B888'],   // Underbelly - lighter
  h: ['#E0B890', '#F0C8A0'],   // Highlight fur

  // Ears
  E: ['#A67B52', '#B88B62'],   // Ear outer
  e: ['#E0A090', '#F0B0A0'],   // Ear inner - pink
  i: ['#D09080', '#E0A090'],   // Ear inner shadow

  // Eyes - Gen Z stare (ㅡ ㅡ) - thin horizontal lines
  n: ['#1A0A00', '#0A0000'],   // Eye line - almost black

  // Nose - BIG and prominent with nostrils
  N: ['#5A3A2A', '#6A4A3A'],   // Nose main
  O: ['#2A1A0A', '#1A0A00'],   // Nostrils - dark holes
  o: ['#4A2A1A', '#5A3A2A'],   // Nose shadow

  // Mouth/Cheek
  m: ['#B08060', '#C09070'],   // Mouth line
  B: ['#E8A090', '#F0B0A0'],   // Blush

  // Gold chain (Investors)
  Q: ['#FFD700', '#FFE040'],   // Gold bright
  q: ['#DAA520', '#EAB530'],   // Gold shadow

  // Laptop - MacBook style
  S: ['#E0E0E0', '#D0D0D0'],   // Silver body
  s: ['#1A1A2E', '#2A2A3E'],   // Screen dark
  g: ['#00FF80', '#40FFA0'],   // Green code
  k: ['#C0C0C0', '#B0B0B0'],   // Keyboard

  // Items
  M: ['#606060', '#707070'],   // Magnifying handle
  L: ['#A0D0F0', '#B0E0FF'],   // Magnifying lens
  R: ['#FF4060', '#FF6080'],   // Heart red
  r: ['#E03050', '#F04060'],   // Heart shadow
  W: ['#F8F8F8', '#E8E8E8'],   // White/paper
  w: ['#80D0FF', '#A0E0FF'],   // Water/sweat
  Z: ['#80C8F0', '#A0D8FF'],   // Zzz
  T: ['#808080', '#909090'],   // Steam
  C: ['#F8F0E8', '#E8E0D8'],   // Coffee cup
  c: ['#4A3020', '#5A4030'],   // Coffee liquid
  K: ['#3A3A3A', '#4A4A4A'],   // Book cover
  P: ['#505050', '#606060'],   // Pen

  // Building
  b: ['#505060', '#606070'],   // Building
  v: ['#404050', '#505060'],   // Window

  // Door
  D: ['#6A5040', '#7A6050'],   // Door
  j: ['#5A4030', '#6A5040'],   // Door shadow
  H: ['#DAA520', '#EAB530'],   // Door handle

  // Gold coins
  G: ['#FFD700', '#FFE040'],   // Gold coin
  $: ['#50B050', '#60C060'],   // Dollar green

  // Alligator
  A: ['#4A7A4A', '#5A8A5A'],   // Body green
  a: ['#3A6A3A', '#4A7A4A'],   // Body shadow
  l: ['#7AAA7A', '#8ABA8A'],   // Belly light
  Y: ['#FFE040', '#FFF060'],   // Eye yellow
  t: ['#F0F0F0', '#E0E0E0'],   // Teeth white
  X: ['#5A8A5A', '#6A9A6A'],   // Spikes
}

function fill(dark: boolean, key: string): string {
  const pair = P[key]
  if (!pair) return 'transparent'
  return dark ? pair[1] : pair[0]
}

// ══════════════════════════════════════════════════════════
// ══ PIXEL ART ENGINE - NO GAPS ══
// ══════════════════════════════════════════════════════════

function parseArt(art: string): { x: number; y: number; c: string }[] {
  const rows = art.trim().split('\n').map(r => r.trimEnd())
  const pixels: { x: number; y: number; c: string }[] = []
  for (let y = 0; y < rows.length; y++)
    for (let x = 0; x < rows[y].length; x++) {
      const ch = rows[y][x]
      if (ch !== '.' && ch !== ' ') pixels.push({ x, y, c: ch })
    }
  return pixels
}

function artSize(art: string): { w: number; h: number } {
  const rows = art.trim().split('\n').map(r => r.trimEnd())
  return { w: Math.max(...rows.map(r => r.length)), h: rows.length }
}

// ══════════════════════════════════════════════════════════
// ══ SVG RENDERER - CRISP PIXELS, NO GAPS ══
// ══════════════════════════════════════════════════════════

function PixelSvg({
  pixels, w, h, dark,
}: {
  pixels: { x: number; y: number; c: string }[]
  w: number
  h: number
  dark: boolean
}) {
  return (
    <svg
      viewBox={`0 0 ${w} ${h}`}
      xmlns="http://www.w3.org/2000/svg"
      className="w-full h-full"
      preserveAspectRatio="xMidYMid meet"
      style={{
        imageRendering: 'pixelated',
        shapeRendering: 'crispEdges',
      }}
    >
      {pixels.map((p, i) => (
        <rect
          key={i}
          x={p.x}
          y={p.y}
          width={1.01}
          height={1.01}
          fill={fill(dark, p.c)}
          style={{ shapeRendering: 'crispEdges' }}
        />
      ))}
    </svg>
  )
}

// ══════════════════════════════════════════════════════════
// ══ HIGH-RES CAPYBARA PIXEL ART (64px base) ══
// Clearly recognizable: squint eyes, big nose, nostrils,
// small ears, chubby body, short legs
// ══════════════════════════════════════════════════════════

// Base capybara - 48x36 detailed
const BASE_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff...........
............FFFFFuuuuuuuuuuuuuuuFFFFFff...........
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...........
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ CODING POSE - With MacBook ══
// ══════════════════════════════════════════════════════════

const CODING_ART = `
................EeeE..........EeeE........................................
...............EeiiE..........EeiiE.......................................
...............EEEE............EEEE.......................................
..............FFFFFFFFFFFFFFFFFFFFFFFFf....................................
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...................................
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..................................
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..................................
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.................................
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.................................
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff................................
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff................................
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff................................
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff................................
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.................................
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.................................
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.................................
...........FFFFFFFFFooooooooFFFFFFFFFfff..................................
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..................................
............FFFFFFFFFFFFFFFFFFFFFFFFfff...................................
............FFFFFuuuuuuuuuuuuuuuFFFFFff...................................
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...SSSSSSSSSSSSSSSSSSSS.............
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff..SssssssssssssssssssssS............
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff..Ssg.gg.g.gg.g.gg.ggg.sS...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff..Ssg.g.g.g.g.g.g..g.g.sS...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff..Ssg.gg.g.gg.g.gg.ggg.sS...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff...SssssssssssssssssssssS............
............FFFFFFFFFFFFFFFFFFFFFFFff....SkkkkkkkkkkkkkkkkkkkkS............
.............FFFFFFFFFFFFFFFFFFFFFFf......SSSSSSSSSSSSSSSSSSSS.............
..............ddddd..........ddddd........................................
.............ffffff..........ffffff.......................................
.............fffff............fffff.......................................
`

// ══════════════════════════════════════════════════════════
// ══ SEARCH POSE - With magnifying glass ══
// ══════════════════════════════════════════════════════════

const SEARCH_ART = `
................EeeE..........EeeE................MMMMMMM
...............EeiiE..........EeiiE..............MLLLLLLM
...............EEEE............EEEE.............MLLLLLLLM
..............FFFFFFFFFFFFFFFFFFFFFFFFf.........MLLLLLLLM
.............FFFFFFFFFFFFFFFFFFFFFFFFFf.........MLLLLLLLM
............FFFFFFFFFFFFFFFFFFFFFFFFFFff.........MMMMMMM
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........M
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........M
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff........M
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff.......M
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff......M
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff.....M
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff....M
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff....M
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff...M
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff..M
...........FFFFFFFFFooooooooFFFFFFFFFfff..M
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff.M
............FFFFFFFFFFFFFFFFFFFFFFFFfff.M
............FFFFFuuuuuuuuuuuuuuuFFFFFff.
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff.
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff.
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff.
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff.
...........FFFuuuuuuuuuuuuuuuuuuFFFffff.
...........FFFFuuuuuuuuuuuuuuuuFFFFfff..
............FFFFFFFFFFFFFFFFFFFFFFFff...
.............FFFFFFFFFFFFFFFFFFFFFFf....
..............ddddd..........ddddd......
.............ffffff..........ffffff.....
.............fffff............fffff.....
`

// ══════════════════════════════════════════════════════════
// ══ BLING POSE - Gold chain (Investors) ══
// ══════════════════════════════════════════════════════════

const BLING_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
.........QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQq.........
.........qQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQq.........
............FFFFFuuuuuuuuuuuuuuuFFFFFff...........
...........FFFFFuQQQQQQQQQQQQQQuFFFFFff...........
..........FFFFuuQqqqqqqqqqqqqqQuuFFFFff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ COIN POSE - Holding gold coins ══
// ══════════════════════════════════════════════════════════

const COIN_ART = `
................EeeE..........EeeE................GGGGG
...............EeiiE..........EeiiE..............GGGGGGG
...............EEEE............EEEE..............GGGGGGG
..............FFFFFFFFFFFFFFFFFFFFFFFFf...........GGGGG
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...............
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..............
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..............
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.............
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.............
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff............
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff............
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff............
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff............
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff......GGGGG..
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.....GGGGGGG.
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.....GGGGGGG.
...........FFFFFFFFFooooooooFFFFFFFFFfff.......GGGGG..
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..............
............FFFFFFFFFFFFFFFFFFFFFFFFfff...............
............FFFFFuuuuuuuuuuuuuuuFFFFFff...............
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...............
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...............
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...............
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...............
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...............
...........FFFFuuuuuuuuuuuuuuuuFFFFfff................
............FFFFFFFFFFFFFFFFFFFFFFFff.................
.............FFFFFFFFFFFFFFFFFFFFFFf..................
..............ddddd..........ddddd....................
.............ffffff..........ffffff...................
.............fffff............fffff...................
`

// ══════════════════════════════════════════════════════════
// ══ HEART POSE - Holding heart ══
// ══════════════════════════════════════════════════════════

const HEART_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff...........
............FFFFFuuuuuuuuuuuuuuuFFFFFff..RRR.RRR..
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff.RRrRRRrRR.
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff.RRRRRRRRR.
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff..RRRRRRR..
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...RRRRR...
...........FFFuuuuuuuuuuuuuuuuuuFFFffff....RRR....
...........FFFFuuuuuuuuuuuuuuuuFFFFfff......R.....
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ COFFEE POSE ══
// ══════════════════════════════════════════════════════════

const COFFEE_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff...TT....
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff..T..T...
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff...TT....
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..CCCC....
............FFFFFFFFFFFFFFFFFFFFFFFFfff..CccccC...
............FFFFFuuuuuuuuuuuuuuuFFFFFff..CccccC...
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff..CccccC...
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...CCCC....
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ SWEATING POSE ══
// ══════════════════════════════════════════════════════════

const SWEATING_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff....w.....
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff...w.....
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff..w......
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff..w.....
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff...........
............FFFFFuuuuuuuuuuuuuuuFFFFFff...........
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...........
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ SLEEPY POSE ══
// ══════════════════════════════════════════════════════════

const SLEEPY_ART = `
................EeeE..........EeeE..........Z.....
...............EeiiE..........EeiiE........Z......
...............EEEE............EEEE.......Z.......
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff...........
............FFFFFuuuuuuuuuuuuuuuFFFFFff...........
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...........
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ QUESTION POSE ══
// ══════════════════════════════════════════════════════════

const QUESTION_ART = `
................EeeE..........EeeE..........WWWW..
...............EeiiE..........EeiiE........W....W.
...............EEEE............EEEE........W....W.
..............FFFFFFFFFFFFFFFFFFFFFFFFf......W....
.............FFFFFFFFFFFFFFFFFFFFFFFFFf.....W.....
............FFFFFFFFFFFFFFFFFFFFFFFFFFff....W.....
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff...W.....
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff...........
............FFFFFuuuuuuuuuuuuuuuFFFFFff...........
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...........
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ MEME POSE - Holding pen ══
// ══════════════════════════════════════════════════════════

const MEME_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff.....P.....
............FFFFFuuuuuuuuuuuuuuuFFFFFff......P....
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff.......P...
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff........P..
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff.........P.
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff..........P
...........FFFuuuuuuuuuuuuuuuuuuFFFffff..........P
...........FFFFuuuuuuuuuuuuuuuuFFFFfff...........P
............FFFFFFFFFFFFFFFFFFFFFFFff............P
.............FFFFFFFFFFFFFFFFFFFFFFf.............P
..............ddddd..........ddddd...............P
.............ffffff..........ffffff.............PP
.............fffff............fffff..............
`

// ══════════════════════════════════════════════════════════
// ══ BUILDING POSE ══
// ══════════════════════════════════════════════════════════

const BUILDING_ART = `
bbbbbbbbbbbbbbbbbbbb................EeeE..........EeeE
bbbvvbbbvvbbbvvbbbbb...............EeiiE..........EeiiE
bbbbbbbbbbbbbbbbbbbb...............EEEE............EEEE
bbbvvbbbvvbbbvvbbbbb..............FFFFFFFFFFFFFFFFFFFFFFFFf
bbbbbbbbbbbbbbbbbbbb.............FFFFFFFFFFFFFFFFFFFFFFFFFf
bbbvvbbbvvbbbvvbbbbb............FFFFFFFFFFFFFFFFFFFFFFFFFFff
bbbbbbbbbbbbbbbbbbbb...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff
bbbvvbbbvvbbbvvbbbbb..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff
bbbbbbbbbbbbbbbbbbbb..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff
bbbvvbbbvvbbbvvbbbbb.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff
bbbbbbbbbbbbbbbbbbbb.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff
bbbvvbbbvvbbbvvbbbbb.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff
bbbbbbbbbbbbbbbbbbbb.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff
bbbvvbbbvvbbbvvbbbbb..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff
bbbbbbbbbbbbbbbbbbbb..........FFFFFFFFoNNNOooONNNoFFFFFFFffff
bbbvvbbbvvbbbvvbbbbb..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff
bbbbbbbbbbbbbbbbbbbb...........FFFFFFFFFooooooooFFFFFFFFFfff
bbbvvbbbvvbbbvvbbbbb...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff
bbbbbbbbbbbbbbbbbbbb............FFFFFFFFFFFFFFFFFFFFFFFFfff
bbbvvbbbvvbbbvvbbbbb............FFFFFuuuuuuuuuuuuuuuFFFFFff
bbbbbbbbbbbbbbbbbbbb...........FFFFFuuuuuuuuuuuuuuuuFFFFFff
bbbvvbbbvvbbbvvbbbbb..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff
bbbbbbbbbbbbbbbbbbbb..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff
bbbvvbbbvvbbbvvbbbbb..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff
bbbbbbbbbbbbbbbbbbbb...........FFFuuuuuuuuuuuuuuuuuuFFFffff
bbbvvbbbvvbbbvvbbbbb...........FFFFuuuuuuuuuuuuuuuuFFFFfff
bbbbbbbbbbbbbbbbbbbb............FFFFFFFFFFFFFFFFFFFFFFFff
bbbvvbbbvvbbbvvbbbbb.............FFFFFFFFFFFFFFFFFFFFFFf
bbbbbbbbbbbbbbbbbbbb..............ddddd..........ddddd
bbbvvbbbvvbbbvvbbbbb.............ffffff..........ffffff
bbbbbbbbbbbbbbbbbbbb.............fffff............fffff
`

// ══════════════════════════════════════════════════════════
// ══ READING POSE ══
// ══════════════════════════════════════════════════════════

const READING_ART = `
................EeeE..........EeeE................
...............EeiiE..........EeiiE...............
...............EEEE............EEEE...............
..............FFFFFFFFFFFFFFFFFFFFFFFFf............
.............FFFFFFFFFFFFFFFFFFFFFFFFFf...........
............FFFFFFFFFFFFFFFFFFFFFFFFFFff..........
...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff..........
..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff.........
..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff.........
.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff........
.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff........
.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff........
..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff.........
..........FFFFFFFFoNNNOooONNNoFFFFFFFffff.........
..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff.........
...........FFFFFFFFFooooooooFFFFFFFFFfff..........
...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff..........
............FFFFFFFFFFFFFFFFFFFFFFFFfff...KKKKKK..
............FFFFFuuuuuuuuuuuuuuuFFFFFff...KWWWWK..
...........FFFFFuuuuuuuuuuuuuuuuFFFFFff...KnnnWK..
..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff...KnnnWK..
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...KKKKKK..
..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff...........
...........FFFuuuuuuuuuuuuuuuuuuFFFffff...........
...........FFFFuuuuuuuuuuuuuuuuFFFFfff............
............FFFFFFFFFFFFFFFFFFFFFFFff.............
.............FFFFFFFFFFFFFFFFFFFFFFf..............
..............ddddd..........ddddd................
.............ffffff..........ffffff...............
.............fffff............fffff...............
`

// ══════════════════════════════════════════════════════════
// ══ DOOR POSE ══
// ══════════════════════════════════════════════════════════

const DOOR_ART = `
DDDDDDD................EeeE..........EeeE
DjjjjjD...............EeiiE..........EeiiE
DjjjjjD...............EEEE............EEEE
DjjjjjD..............FFFFFFFFFFFFFFFFFFFFFFFFf
DjjjjjD.............FFFFFFFFFFFFFFFFFFFFFFFFFf
DjjjjjD............FFFFFFFFFFFFFFFFFFFFFFFFFFff
DjjHjjD...........FFFFFFFFFFFFFFFFFFFFFFFFFFFff
DjjjjjD..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff
DjjjjjD..........FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff
DjjjjjD.........FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff
DjjjjjD.........FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff
DjjjjjD.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff
DjjjjjD.........BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff
DjjjjjD..........FFFFFFFFFoooNNNNNoooFFFFFFFFfff
DjjjjjD..........FFFFFFFFoNNNOooONNNoFFFFFFFffff
DjjjjjD..........FFFFFFFFFoNNNNNNNNoFFFFFFFFffff
DjjjjjD...........FFFFFFFFFooooooooFFFFFFFFFfff
DjjjjjD...........FFFFFFFFFFFFmmFFFFFFFFFFFFfff
DjjjjjD............FFFFFFFFFFFFFFFFFFFFFFFFfff
DjjjjjD............FFFFFuuuuuuuuuuuuuuuFFFFFff
DjjjjjD...........FFFFFuuuuuuuuuuuuuuuuFFFFFff
DjjjjjD..........FFFFuuuuuuuuuuuuuuuuuuuFFFFff
DjjjjjD..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff
DjjjjjD..........FFFuuuuuuuuuuuuuuuuuuuuFFFfff
DjjjjjD...........FFFuuuuuuuuuuuuuuuuuuFFFffff
DjjjjjD...........FFFFuuuuuuuuuuuuuuuuFFFFfff
DjjjjjD............FFFFFFFFFFFFFFFFFFFFFFFff
DjjjjjD.............FFFFFFFFFFFFFFFFFFFFFFf
DjjjjjD..............ddddd..........ddddd
DjjjjjD.............ffffff..........ffffff
DDDDDDD.............fffff............fffff
`

// ══════════════════════════════════════════════════════════
// ══ ECOSYSTEM POSE - Riding alligator (side view) ══
// ══════════════════════════════════════════════════════════

const ECOSYSTEM_ART = `
..........................................EeeE..........EeeE..........................................
.........................................EeiiE..........EeiiE.........................................
.........................................EEEE............EEEE.........................................
........................................FFFFFFFFFFFFFFFFFFFFFFFFf......................................
.......................................FFFFFFFFFFFFFFFFFFFFFFFFFf.....................................
......................................FFFFFFFFFFFFFFFFFFFFFFFFFFff....................................
.....................................FFFFFFFFFFFFFFFFFFFFFFFFFFFff....................................
....................................FFFFFFFFFFFFFFFFFFFFFFFFFFFFfff...................................
....................................FFFFFhhhFFFFFFFFFFFFFhhhFFFFfff...................................
...................................FFFFFhhhhhFFFFFFFFFFFhhhhhFFFffff..................................
...................................FFFFFnnnnnFFFFFFFFFFFnnnnnFFFffff..................................
...................................BFFFFFFFFFFFFFFFFFFFFFFFFFFFFBfff..................................
...................................BFFFFFFFFFFFFFFFFFFFFFFFFFFFBffff..................................
....................................FFFFFFFFFoooNNNNNoooFFFFFFFFfff...................................
....................................FFFFFFFFoNNNOooONNNoFFFFFFFffff...................................
....................................FFFFFFFFFoNNNNNNNNoFFFFFFFFffff...................................
.....................................FFFFFFFFFooooooooFFFFFFFFFfff....................................
.....................................FFFFFFFFFFFFmmFFFFFFFFFFFFfff....................................
.............X..X..X..X..X..X..X..X..FFFFuuuuuuuuuuuuuuuuuuFFFF..X..X..X..X..X..X..X.......XYYYX......
.........aaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAtt.
........aAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAt
.......aAAlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllAAAAAAt
.......aAlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllAAAAAt
......aAllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllAAAAAt
......aAlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllAAAAAAt
.......aaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAt.
........aaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAt.
...........aa..aa................aa..aa................aa..aa................aa..aa.......aa..aa.....
`

// ══════════════════════════════════════════════════════════
// ══ POSE COMPONENTS ══
// ══════════════════════════════════════════════════════════

function BlankPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(BASE_ART)
  const size = artSize(BASE_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function CodingPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(CODING_ART)
  const size = artSize(CODING_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function SearchPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(SEARCH_ART)
  const size = artSize(SEARCH_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function BlingPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(BLING_ART)
  const size = artSize(BLING_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function CoinPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(COIN_ART)
  const size = artSize(COIN_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function HeartPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(HEART_ART)
  const size = artSize(HEART_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function CoffeePose({ dark }: { dark: boolean }) {
  const pixels = parseArt(COFFEE_ART)
  const size = artSize(COFFEE_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function SweatingPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(SWEATING_ART)
  const size = artSize(SWEATING_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function SleepyPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(SLEEPY_ART)
  const size = artSize(SLEEPY_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function QuestionPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(QUESTION_ART)
  const size = artSize(QUESTION_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function MemePose({ dark }: { dark: boolean }) {
  const pixels = parseArt(MEME_ART)
  const size = artSize(MEME_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function BuildingPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(BUILDING_ART)
  const size = artSize(BUILDING_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function ReadingPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(READING_ART)
  const size = artSize(READING_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function DoorPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(DOOR_ART)
  const size = artSize(DOOR_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

function EcosystemPose({ dark }: { dark: boolean }) {
  const pixels = parseArt(ECOSYSTEM_ART)
  const size = artSize(ECOSYSTEM_ART)
  return <PixelSvg pixels={pixels} w={size.w} h={size.h} dark={dark} />
}

// Aliases
function DejectedPose({ dark }: { dark: boolean }) {
  return <SweatingPose dark={dark} />
}

function SparklePose({ dark }: { dark: boolean }) {
  return <HeartPose dark={dark} />
}

function SmokingPose({ dark }: { dark: boolean }) {
  return <CoffeePose dark={dark} />
}

function EatingPose({ dark }: { dark: boolean }) {
  return <CoffeePose dark={dark} />
}

function WinkPose({ dark }: { dark: boolean }) {
  return <BlankPose dark={dark} />
}

// ══════════════════════════════════════════════════════════
// ══ POSE REGISTRY ══
// ══════════════════════════════════════════════════════════

const POSES: Record<string, (props: { dark: boolean }) => React.ReactNode> = {
  blank: BlankPose,
  coding: CodingPose,
  heroLaptop: CodingPose,
  search: SearchPose,
  bling: BlingPose,
  coin: CoinPose,
  building: BuildingPose,
  reading: ReadingPose,
  heart: HeartPose,
  ecosystem: EcosystemPose,
  question: QuestionPose,
  sweating: SweatingPose,
  coffee: CoffeePose,
  door: DoorPose,
  meme: MemePose,
  sleepy: SleepyPose,
  dejected: DejectedPose,
  sparkle: SparklePose,
  smoking: SmokingPose,
  eating: EatingPose,
  wink: WinkPose,
  main: CodingPose,
  careers: SearchPose,
  investors: BlingPose,
  companies: BuildingPose,
  articles: ReadingPose,
  bookmarks: HeartPose,
  login: DoorPose,
  loading: CoffeePose,
  notfound: QuestionPose,
  empty: QuestionPose,
  success: HeartPose,
  error: SweatingPose,
}

// ══════════════════════════════════════════════════════════
// ══ MEME CONTENT ══
// ══════════════════════════════════════════════════════════

const CLICK_QUOTES = [
  'bruh', 'no cap', 'slay', 'its giving... employed',
  'bestie ur hired', 'periodt', 'lowkey fire', 'real',
  'ser pls', 'gm', 'wagmi', 'ngmi fr', 'wen lambo',
  'probably nothing', 'few understand', 'touch grass',
]

const TSUNDERE_MSGS = [
  '뭘 봐...', '...', '*stares*', '별로야.',
  'mid tbh', '...관심 없어', 'ok and?', 'hm.',
]

export const TIME_MSGS: Record<TimeOfDay, string> = {
  dawn: 'why are you here at this hour...',
  morning: 'gm anon',
  lunch: '*munch munch*',
  afternoon: '...',
  evening: '퇴근하고 싶다...',
  night: 'this is fine',
}

// ══════════════════════════════════════════════════════════
// ══ MAIN COMPONENT ══
// ══════════════════════════════════════════════════════════

let globalClicks = 0
let easterEggTriggered = false

export default function Pixelbara({ pose, size = 120, className = '', clickable = false, suppressHover = false }: PixelbaraProps) {
  const dark = useIsDark()
  const [hoverMsg, setHoverMsg] = useState<string | null>(null)
  const PoseComponent = POSES[pose] ?? POSES.blank

  const handleClick = useCallback(() => {
    if (!clickable) return
    globalClicks++
    if (globalClicks === 10 && !easterEggTriggered) {
      easterEggTriggered = true
      toast('YOU FOUND THE ALPHA', {
        description: 'Hidden role: Chief Capybara Officer at Pixelbara Labs. DM us.',
        duration: 8000,
      })
      return
    }
    const quote = CLICK_QUOTES[Math.floor(Math.random() * CLICK_QUOTES.length)]
    toast(quote, { duration: 2000, className: 'text-sm font-bold tracking-wide' })
  }, [clickable])

  const handleMouseEnter = useCallback(() => {
    if (!clickable || suppressHover) return
    const msg = TSUNDERE_MSGS[Math.floor(Math.random() * TSUNDERE_MSGS.length)]
    setHoverMsg(msg)
  }, [clickable, suppressHover])

  const handleMouseLeave = useCallback(() => setHoverMsg(null), [])

  return (
    <div
      className={`relative inline-block select-none ${clickable ? 'cursor-pointer hover:scale-105 active:scale-95 transition-transform' : ''} ${className}`}
      style={{
        width: size,
        imageRendering: 'pixelated',
      }}
      aria-label={`Pixelbara mascot - ${pose}`}
      role="img"
      onClick={clickable ? handleClick : undefined}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      {hoverMsg && (
        <span className="absolute -top-6 left-1/2 -translate-x-1/2 px-2 py-0.5 text-[10px] whitespace-nowrap bg-a24-text dark:bg-a24-dark-text text-white dark:text-a24-dark-bg z-50 pointer-events-none">
          {hoverMsg}
        </span>
      )}
      <PoseComponent dark={dark} />
    </div>
  )
}

// ══════════════════════════════════════════════════════════
// ══ VARIANT COMPONENTS ══
// ══════════════════════════════════════════════════════════

export function TimeAwarePixelbara(props: Omit<PixelbaraProps, 'pose'>) {
  const time = useTimeOfDay()
  const pose = useMemo((): PoseId => {
    switch (time) {
      case 'dawn': return 'sleepy'
      case 'lunch': return 'coffee'
      case 'evening': return 'sweating'
      default: return 'coding'
    }
  }, [time])
  return <Pixelbara {...props} pose={pose} />
}

// Mini version
export function MiniPixelbara({ className = '' }: { className?: string }) {
  const dark = useIsDark()
  const miniArt = `
....EeE......EeE....
...FFFFFFFFFFFFFF...
..FFFFhhhFFhhhFFFF..
..FFFFnnnFFnnnFFFF..
...FFFFoNNNNoFFFF...
....FFuuuuuuuuFF....
....FFuuuuuuuuFF....
.....fff..fff.......
`
  const pixels = parseArt(miniArt)
  const { w, h } = artSize(miniArt)
  return (
    <span className={`inline-block ${className}`} style={{ width: 32, height: 20, imageRendering: 'pixelated' }}>
      <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-full" style={{ imageRendering: 'pixelated', shapeRendering: 'crispEdges' }}>
        {pixels.map((p, i) => (
          <rect key={i} x={p.x} y={p.y} width={1.01} height={1.01} fill={fill(dark, p.c)} style={{ shapeRendering: 'crispEdges' }} />
        ))}
      </svg>
    </span>
  )
}

export function PixelbaraToggleIcon({ className = '' }: { className?: string }) {
  const dark = useIsDark()
  const miniArt = `
....EeE......EeE....
...FFFFFFFFFFFFFF...
..FFFFhhhFFhhhFFFF..
..FFFFnnnFFnnnFFFF..
...FFFFoNNNNoFFFF...
....FFuuuuuuuuFF....
....FFuuuuuuuuFF....
.....fff..fff.......
`
  const pixels = parseArt(miniArt)
  const { w, h } = artSize(miniArt)
  return (
    <span className={`inline-block ${className}`} style={{ width: 32, height: 20, imageRendering: 'pixelated' }}>
      <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-full" style={{ imageRendering: 'pixelated', shapeRendering: 'crispEdges' }}>
        {pixels.map((p, i) => (
          <rect key={i} x={p.x} y={p.y} width={1.01} height={1.01} fill={fill(dark, p.c)} style={{ shapeRendering: 'crispEdges' }} />
        ))}
      </svg>
    </span>
  )
}

// ══════════════════════════════════════════════════════════
// ══ EXPORTS ══
// ══════════════════════════════════════════════════════════

export { useTimeOfDay }
export type { TimeOfDay, PoseId, PoseAlias }
