/**
 * Priority Companies Registry
 * Web3 companies with VC backing and metadata
 * Korean + Global coverage from top VC portfolios
 */

export type CareerPlatform = 'lever' | 'greenhouse' | 'ashby' | 'wanted' | 'notion' | null

export interface PriorityCompany {
  name: string;
  aliases: string[];
  tier: 'P0' | 'P1' | 'P2';
  backers: string[];
  sector: string;
  office_location: string;
  hasToken: boolean;
  stage: string;
  careerUrl: string | null;
  careerPlatform: CareerPlatform;
}

export const PRIORITY_COMPANIES: PriorityCompany[] = [
  // ════════════════════════════════════════════
  // P0: TOP-TIER COMPANIES
  // ════════════════════════════════════════════

  // ── P0: Korean ──
  {
    name: 'Hashed',
    aliases: ['hashed.com', 'Hashed Fund'],
    tier: 'P0',
    backers: ['Hashed'],
    sector: 'VC / Investment',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/hashed',
    careerPlatform: 'lever',
  },
  {
    name: 'DSRV',
    aliases: ['dsrvlabs', 'DSRV Labs'],
    tier: 'P0',
    backers: ['Hashed', 'Kakao Ventures'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'CryptoQuant',
    aliases: ['cryptoquant.com'],
    tier: 'P0',
    backers: ['Hashed', 'Mirae Asset'],
    sector: 'Analytics / Data',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series B',
    careerUrl: 'https://jobs.lever.co/cryptoquant',
    careerPlatform: 'lever',
  },
  {
    name: 'Klaytn',
    aliases: ['Kaia', 'klaytn.foundation', 'Kaia Foundation'],
    tier: 'P0',
    backers: ['Kakao'],
    sector: 'Layer 1',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Wemade',
    aliases: ['WEMIX', 'wemade.com', 'wemix.com'],
    tier: 'P0',
    backers: ['Wemade'],
    sector: 'Gaming / Metaverse',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Public',
    careerUrl: 'https://www.wanted.co.kr/company/4137',
    careerPlatform: 'wanted',
  },
  {
    name: 'LINE NEXT',
    aliases: ['LINE', 'DOSI', 'Finschia', 'line-next'],
    tier: 'P0',
    backers: ['LINE Corporation'],
    sector: 'Platform / NFT',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Dunamu',
    aliases: ['Upbit', 'dunamu.com', 'upbit.com'],
    tier: 'P0',
    backers: ['Dunamu'],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/79',
    careerPlatform: 'wanted',
  },

  // ── P0: Global ──
  {
    name: 'Coinbase',
    aliases: ['coinbase.com'],
    tier: 'P0',
    backers: ['a16z', 'Paradigm', 'Tiger Global'],
    sector: 'Exchange',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Public',
    careerUrl: 'https://www.coinbase.com/careers/positions',
    careerPlatform: null,
  },
  {
    name: 'Binance',
    aliases: ['binance.com', 'BNB Chain'],
    tier: 'P0',
    backers: ['Binance'],
    sector: 'Exchange',
    office_location: 'Global / Dubai',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.binance.com/en/careers',
    careerPlatform: null,
  },
  {
    name: 'Uniswap Labs',
    aliases: ['uniswap.org', 'Uniswap'],
    tier: 'P0',
    backers: ['a16z', 'Paradigm', 'Polychain'],
    sector: 'DeFi',
    office_location: 'New York, USA',
    hasToken: true,
    stage: 'Series B',
    careerUrl: 'https://boards.greenhouse.io/uniswaplabs',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'OpenSea',
    aliases: ['opensea.io'],
    tier: 'P0',
    backers: ['a16z', 'Paradigm', 'Coatue'],
    sector: 'NFT Marketplace',
    office_location: 'New York, USA',
    hasToken: false,
    stage: 'Series C',
    careerUrl: 'https://jobs.lever.co/OpenSea',
    careerPlatform: 'lever',
  },
  {
    name: 'Chainlink Labs',
    aliases: ['chainlink', 'chain.link'],
    tier: 'P0',
    backers: ['Framework Ventures', 'Paradigm'],
    sector: 'Oracle / Infrastructure',
    office_location: 'Remote / Global',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/chainlink',
    careerPlatform: 'lever',
  },
  {
    name: 'Circle',
    aliases: ['circle.com', 'USDC'],
    tier: 'P0',
    backers: ['Goldman Sachs', 'Fidelity', 'BlackRock'],
    sector: 'Stablecoin / Payments',
    office_location: 'Boston, USA',
    hasToken: false,
    stage: 'Pre-IPO',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Consensys',
    aliases: ['consensys.net', 'MetaMask', 'Infura', 'Linea'],
    tier: 'P0',
    backers: ['a16z', 'Paradigm', 'SoftBank'],
    sector: 'Infrastructure',
    office_location: 'New York, USA',
    hasToken: false,
    stage: 'Series D',
    careerUrl: 'https://consensys.io/open-roles',
    careerPlatform: null,
  },
  {
    name: 'Alchemy',
    aliases: ['alchemy.com'],
    tier: 'P0',
    backers: ['a16z', 'Lightspeed', 'Coatue'],
    sector: 'Infrastructure',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Series C',
    careerUrl: 'https://boards.greenhouse.io/alchemy',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Polygon Labs',
    aliases: ['polygon.technology', 'Polygon', 'MATIC'],
    tier: 'P0',
    backers: ['Sequoia Capital', 'SoftBank'],
    sector: 'Layer 2',
    office_location: 'Remote / Global',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Offchain Labs',
    aliases: ['Arbitrum', 'offchainlabs.com'],
    tier: 'P0',
    backers: ['Lightspeed', 'Polychain', 'Pantera'],
    sector: 'Layer 2',
    office_location: 'New York, USA',
    hasToken: true,
    stage: 'Series B',
    careerUrl: 'https://jobs.lever.co/offchainlabs',
    careerPlatform: 'lever',
  },
  {
    name: 'Arbitrum Foundation',
    aliases: ['arbitrum.foundation'],
    tier: 'P0',
    backers: ['Offchain Labs'],
    sector: 'Layer 2',
    office_location: 'George Town, Cayman Islands',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/arbitrumfoundation',
    careerPlatform: 'lever',
  },
  {
    name: 'OP Labs',
    aliases: ['Optimism', 'optimism.io'],
    tier: 'P0',
    backers: ['a16z', 'Paradigm'],
    sector: 'Layer 2',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Base',
    aliases: ['base.org', 'Base Chain'],
    tier: 'P0',
    backers: ['Coinbase'],
    sector: 'Layer 2',
    office_location: 'Remote',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://boards.greenhouse.io/basejobs',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Solana Foundation',
    aliases: ['solana.com', 'Solana', 'Solana Labs'],
    tier: 'P0',
    backers: ['a16z', 'Polychain', 'Multicoin'],
    sector: 'Layer 1',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://jobs.solana.com/companies/solana-labs',
    careerPlatform: null,
  },
  {
    name: 'Mysten Labs',
    aliases: ['Sui', 'sui.io', 'mystenlabs.com'],
    tier: 'P0',
    backers: ['a16z', 'Lightspeed', 'Samsung Next'],
    sector: 'Layer 1',
    office_location: 'Palo Alto, USA',
    hasToken: true,
    stage: 'Series B',
    careerUrl: 'https://jobs.lever.co/mystenlabs',
    careerPlatform: 'lever',
  },
  {
    name: 'Aptos Labs',
    aliases: ['aptoslabs.com', 'Aptos'],
    tier: 'P0',
    backers: ['a16z', 'Multicoin', 'Hashed'],
    sector: 'Layer 1',
    office_location: 'Palo Alto, USA',
    hasToken: true,
    stage: 'Series A',
    careerUrl: 'https://boards.greenhouse.io/aptoslabs',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Ripple',
    aliases: ['ripple.com', 'XRP'],
    tier: 'P0',
    backers: ['a16z', 'Google Ventures'],
    sector: 'Payments',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://ripple.com/careers',
    careerPlatform: null,
  },
  {
    name: 'Fireblocks',
    aliases: ['fireblocks.com'],
    tier: 'P0',
    backers: ['Paradigm', 'Sequoia', 'Coatue'],
    sector: 'Security / Custody',
    office_location: 'New York, USA',
    hasToken: false,
    stage: 'Series E',
    careerUrl: 'https://boards.greenhouse.io/fireblocks',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Chainalysis',
    aliases: ['chainalysis.com'],
    tier: 'P0',
    backers: ['Benchmark', 'Accel', 'GIC'],
    sector: 'Analytics / Compliance',
    office_location: 'New York, USA',
    hasToken: false,
    stage: 'Series F',
    careerUrl: null,
    careerPlatform: null,
  },

  // ════════════════════════════════════════════
  // P1: STRONG COMPANIES
  // ════════════════════════════════════════════

  // ── P1: Korean ──
  {
    name: 'Bithumb',
    aliases: ['bithumb.com', 'Bithumb Korea'],
    tier: 'P1',
    backers: [],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/203',
    careerPlatform: 'wanted',
  },
  {
    name: 'Korbit',
    aliases: ['korbit.co.kr'],
    tier: 'P1',
    backers: ['SoftBank', 'Kakao Ventures'],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/1017',
    careerPlatform: 'wanted',
  },
  {
    name: 'Ozys',
    aliases: ['ozys.io', 'KLAYswap', 'Orbit Bridge'],
    tier: 'P1',
    backers: [],
    sector: 'DeFi',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/9498',
    careerPlatform: 'wanted',
  },
  {
    name: 'Planetarium',
    aliases: ['planetariumhq', 'Nine Chronicles', 'planetarium.dev'],
    tier: 'P1',
    backers: ['Hashed', 'Animoca Brands'],
    sector: 'Gaming',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'NFTBank',
    aliases: ['nftbank.ai'],
    tier: 'P1',
    backers: ['Hashed', 'a16z'],
    sector: 'Analytics / NFT',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: 'https://jobs.lever.co/nftbank',
    careerPlatform: 'lever',
  },
  {
    name: 'Lambda256',
    aliases: ['lambda256.io', 'Luniverse'],
    tier: 'P1',
    backers: ['Dunamu'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/8052',
    careerPlatform: 'wanted',
  },
  {
    name: 'Ground X',
    aliases: ['groundx.xyz', 'GroundX'],
    tier: 'P1',
    backers: ['Kakao'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/5091',
    careerPlatform: 'wanted',
  },
  {
    name: 'ICONLOOP',
    aliases: ['iconloop.com', 'ICON', 'iconloop'],
    tier: 'P1',
    backers: [],
    sector: 'Layer 1',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/5380',
    careerPlatform: 'wanted',
  },
  {
    name: 'Cosmostation',
    aliases: ['cosmostation.io'],
    tier: 'P1',
    backers: ['Hashed'],
    sector: 'Infrastructure / Wallet',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://cosmostation.notion.site/careers',
    careerPlatform: 'notion',
  },
  {
    name: 'Xangle',
    aliases: ['xangle.io'],
    tier: 'P1',
    backers: ['Hashed', 'KB Investment'],
    sector: 'Analytics / Data',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: 'https://www.wanted.co.kr/company/5827',
    careerPlatform: 'wanted',
  },
  {
    name: 'DeSpread',
    aliases: ['despread.io'],
    tier: 'P1',
    backers: [],
    sector: 'Consulting / Marketing',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://despread.notion.site/careers',
    careerPlatform: 'notion',
  },
  {
    name: 'ChainPartners',
    aliases: ['chainpartners.co', 'Chain Partners'],
    tier: 'P1',
    backers: [],
    sector: 'VC / Advisory',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Superblock',
    aliases: ['superblock.co'],
    tier: 'P1',
    backers: [],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Coinone',
    aliases: ['coinone.co.kr'],
    tier: 'P1',
    backers: [],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/258',
    careerPlatform: 'wanted',
  },
  {
    name: 'Blocko',
    aliases: ['blocko.io', 'AERGO'],
    tier: 'P1',
    backers: ['Samsung'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/3161',
    careerPlatform: 'wanted',
  },
  {
    name: 'Haechi Labs',
    aliases: ['haechi.io', 'Haechi Audit'],
    tier: 'P1',
    backers: ['Hashed'],
    sector: 'Security / Audit',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Bifrost',
    aliases: ['bifrost.finance', 'BFC'],
    tier: 'P1',
    backers: ['Hashed'],
    sector: 'DeFi / Staking',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Kroma',
    aliases: ['kroma.network'],
    tier: 'P1',
    backers: ['Hashed'],
    sector: 'Layer 2',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'UNOPND',
    aliases: ['unopnd.com'],
    tier: 'P1',
    backers: ['Hashed'],
    sector: 'Incubator / Accelerator',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },

  // ── P1: Global ──
  {
    name: 'Kraken',
    aliases: ['kraken.com'],
    tier: 'P1',
    backers: [],
    sector: 'Exchange',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/kraken',
    careerPlatform: 'lever',
  },
  {
    name: 'OKX',
    aliases: ['okx.com', 'OKEx'],
    tier: 'P1',
    backers: [],
    sector: 'Exchange',
    office_location: 'Global / Dubai',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.okx.com/careers',
    careerPlatform: null,
  },
  {
    name: 'Crypto.com',
    aliases: ['crypto.com', 'CRO'],
    tier: 'P1',
    backers: [],
    sector: 'Exchange',
    office_location: 'Singapore',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://crypto.com/careers',
    careerPlatform: null,
  },
  {
    name: 'Aave',
    aliases: ['aave.com', 'Aave Labs'],
    tier: 'P1',
    backers: ['Blockchain Capital', 'Standard Crypto'],
    sector: 'DeFi',
    office_location: 'London, UK',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/aave',
    careerPlatform: 'lever',
  },
  {
    name: 'dYdX',
    aliases: ['dydx.exchange'],
    tier: 'P1',
    backers: ['a16z', 'Paradigm', 'Polychain'],
    sector: 'DeFi / DEX',
    office_location: 'New York, USA',
    hasToken: true,
    stage: 'Series C',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Lido Finance',
    aliases: ['lido.fi', 'Lido'],
    tier: 'P1',
    backers: ['a16z', 'Paradigm', 'Dragonfly'],
    sector: 'DeFi / Staking',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Eigen Labs',
    aliases: ['eigenlayer.xyz', 'EigenLayer'],
    tier: 'P1',
    backers: ['a16z', 'Polychain'],
    sector: 'Infrastructure',
    office_location: 'Seattle, USA',
    hasToken: true,
    stage: 'Series A',
    careerUrl: 'https://jobs.lever.co/eigenlabs',
    careerPlatform: 'lever',
  },
  {
    name: 'StarkWare',
    aliases: ['starkware.co', 'Starknet', 'StarkEx'],
    tier: 'P1',
    backers: ['Paradigm', 'Sequoia', 'Coatue'],
    sector: 'Layer 2',
    office_location: 'Tel Aviv, Israel',
    hasToken: true,
    stage: 'Series D',
    careerUrl: 'https://starkware.co/careers/',
    careerPlatform: null,
  },
  {
    name: 'Matter Labs',
    aliases: ['matter-labs.io', 'zkSync', 'ZKsync'],
    tier: 'P1',
    backers: ['a16z', 'Dragonfly', 'Blockchain Capital'],
    sector: 'Layer 2',
    office_location: 'Berlin, Germany',
    hasToken: true,
    stage: 'Series C',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Celestia Labs',
    aliases: ['celestia.org', 'Celestia'],
    tier: 'P1',
    backers: ['Polychain', 'Bain Capital Crypto'],
    sector: 'Infrastructure / Modular',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series A+',
    careerUrl: 'https://jobs.lever.co/celestia',
    careerPlatform: 'lever',
  },
  {
    name: 'LayerZero Labs',
    aliases: ['layerzero.network', 'LayerZero'],
    tier: 'P1',
    backers: ['a16z', 'Sequoia', 'Samsung Next'],
    sector: 'Cross-chain',
    office_location: 'Vancouver, Canada',
    hasToken: true,
    stage: 'Series B',
    careerUrl: 'https://boards.greenhouse.io/layerzerolabs',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Ava Labs',
    aliases: ['avalabs.org', 'Avalanche', 'AVAX'],
    tier: 'P1',
    backers: ['a16z', 'Polychain', 'Galaxy Digital'],
    sector: 'Layer 1',
    office_location: 'Brooklyn, USA',
    hasToken: true,
    stage: 'Series C',
    careerUrl: 'https://boards.greenhouse.io/avalabs',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Cosmos Labs',
    aliases: ['cosmos.network', 'Cosmos', 'ATOM'],
    tier: 'P1',
    backers: ['Paradigm', 'Bain Capital Crypto'],
    sector: 'Layer 0 / Infrastructure',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://boards.greenhouse.io/cosmoslabs',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'NEAR Foundation',
    aliases: ['near.org', 'NEAR Protocol', 'NEAR'],
    tier: 'P1',
    backers: ['a16z', 'Pantera', 'Dragonfly'],
    sector: 'Layer 1',
    office_location: 'Remote / Zurich',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'The Graph',
    aliases: ['thegraph.com', 'Graph Protocol', 'GRT'],
    tier: 'P1',
    backers: ['Multicoin', 'Coinbase Ventures'],
    sector: 'Data / Indexing',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Protocol Labs',
    aliases: ['protocol.ai', 'Filecoin', 'IPFS'],
    tier: 'P1',
    backers: ['a16z', 'Sequoia', 'Union Square Ventures'],
    sector: 'Storage / Infrastructure',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Phantom',
    aliases: ['phantom.app'],
    tier: 'P1',
    backers: ['a16z', 'Paradigm'],
    sector: 'Wallet',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Series C',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Safe',
    aliases: ['safe.global', 'Gnosis Safe'],
    tier: 'P1',
    backers: ['Paradigm', '1kx'],
    sector: 'Wallet / Security',
    office_location: 'Berlin, Germany',
    hasToken: true,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Ledger',
    aliases: ['ledger.com'],
    tier: 'P1',
    backers: ['Cathay Innovation', '10T Holdings'],
    sector: 'Hardware Wallet',
    office_location: 'Paris, France',
    hasToken: false,
    stage: 'Series C',
    careerUrl: 'https://www.ledger.com/careers',
    careerPlatform: null,
  },
  {
    name: 'Nansen',
    aliases: ['nansen.ai'],
    tier: 'P1',
    backers: ['a16z', 'Accel'],
    sector: 'Analytics / Data',
    office_location: 'Singapore',
    hasToken: false,
    stage: 'Series B',
    careerUrl: 'https://boards.greenhouse.io/nansen',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Dune Analytics',
    aliases: ['dune.com', 'Dune'],
    tier: 'P1',
    backers: ['Multicoin', 'Dragonfly'],
    sector: 'Analytics / Data',
    office_location: 'Oslo, Norway',
    hasToken: false,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Immutable',
    aliases: ['immutable.com', 'ImmutableX', 'IMX'],
    tier: 'P1',
    backers: ['a16z', 'Paradigm'],
    sector: 'Gaming / NFT',
    office_location: 'Sydney, Australia',
    hasToken: true,
    stage: 'Series C',
    careerUrl: 'https://jobs.lever.co/immutable',
    careerPlatform: 'lever',
  },
  {
    name: 'Animoca Brands',
    aliases: ['animocabrands.com'],
    tier: 'P1',
    backers: ['Temasek', 'GIC'],
    sector: 'Gaming / Investment',
    office_location: 'Hong Kong',
    hasToken: false,
    stage: 'Pre-IPO',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Monad Labs',
    aliases: ['monad.xyz', 'Monad'],
    tier: 'P1',
    backers: ['Paradigm', 'Dragonfly'],
    sector: 'Layer 1',
    office_location: 'New York, USA',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Ethena Labs',
    aliases: ['ethena.fi', 'Ethena'],
    tier: 'P1',
    backers: ['Dragonfly', 'Arthur Hayes'],
    sector: 'DeFi',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Flashbots',
    aliases: ['flashbots.net'],
    tier: 'P1',
    backers: ['Paradigm'],
    sector: 'Infrastructure / MEV',
    office_location: 'Remote',
    hasToken: false,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'MoonPay',
    aliases: ['moonpay.com'],
    tier: 'P1',
    backers: ['Tiger Global', 'Paradigm', 'Coatue'],
    sector: 'Payments / On-ramp',
    office_location: 'Miami, USA',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Paxos',
    aliases: ['paxos.com', 'PYUSD'],
    tier: 'P1',
    backers: ['Oak HC/FT', 'Declaration Partners'],
    sector: 'Stablecoin / Infrastructure',
    office_location: 'New York, USA',
    hasToken: false,
    stage: 'Series D',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'OpenZeppelin',
    aliases: ['openzeppelin.com'],
    tier: 'P1',
    backers: ['a16z', 'Coinbase Ventures'],
    sector: 'Security',
    office_location: 'Remote',
    hasToken: false,
    stage: 'Series B',
    careerUrl: 'https://boards.greenhouse.io/openzeppelin',
    careerPlatform: 'greenhouse',
  },

  // ════════════════════════════════════════════
  // P2: GROWING / EMERGING COMPANIES
  // ════════════════════════════════════════════

  // ── P2: Korean ──
  {
    name: 'Yooldo',
    aliases: ['yooldo.gg'],
    tier: 'P2',
    backers: ['Animoca Brands'],
    sector: 'Gaming',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Seed',
    careerUrl: 'https://yooldo.notion.site/careers',
    careerPlatform: 'notion',
  },
  {
    name: 'Presto Labs',
    aliases: ['presto.com', 'Presto'],
    tier: 'P2',
    backers: [],
    sector: 'Trading / Market Making',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/presto',
    careerPlatform: 'lever',
  },
  {
    name: 'Streami',
    aliases: ['streami.co', 'Gopax parent'],
    tier: 'P2',
    backers: [],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/7854',
    careerPlatform: 'wanted',
  },
  {
    name: 'Crescendo',
    aliases: ['crescendo.finance'],
    tier: 'P2',
    backers: [],
    sector: 'DeFi',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Standard Protocol',
    aliases: ['standardprotocol.org'],
    tier: 'P2',
    backers: [],
    sector: 'DeFi',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Somesing',
    aliases: ['somesing.io'],
    tier: 'P2',
    backers: [],
    sector: 'Social / Music',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Sandbox Network',
    aliases: ['sandbox.co.kr', 'Sandbox'],
    tier: 'P2',
    backers: [],
    sector: 'Media / Creator',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/3508',
    careerPlatform: 'wanted',
  },
  {
    name: 'Gopax',
    aliases: ['gopax.co.kr'],
    tier: 'P2',
    backers: ['Binance'],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/7854',
    careerPlatform: 'wanted',
  },
  {
    name: 'Kakao Games',
    aliases: ['BORA', 'kakaogames.com', 'bora.eco'],
    tier: 'P2',
    backers: ['Kakao'],
    sector: 'Gaming / Metaverse',
    office_location: 'Seongnam, South Korea',
    hasToken: true,
    stage: 'Public',
    careerUrl: 'https://www.wanted.co.kr/company/284',
    careerPlatform: 'wanted',
  },
  {
    name: 'Hexlant',
    aliases: ['hexlant.com'],
    tier: 'P2',
    backers: [],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Iskra',
    aliases: ['iskra.world'],
    tier: 'P2',
    backers: ['Hashed', 'Kakao Ventures'],
    sector: 'Gaming',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Nodit',
    aliases: ['nodit.io'],
    tier: 'P2',
    backers: ['Hashed'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },

  // ── P2: Global ──
  {
    name: 'Magic Eden',
    aliases: ['magiceden.io'],
    tier: 'P2',
    backers: ['Paradigm', 'Sequoia', 'Greylock'],
    sector: 'NFT Marketplace',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Story Protocol',
    aliases: ['storyprotocol.xyz', 'Story'],
    tier: 'P2',
    backers: ['a16z', 'Polychain'],
    sector: 'IP / Infrastructure',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series B',
    careerUrl: 'https://jobs.lever.co/storyprotocol',
    careerPlatform: 'lever',
  },
  {
    name: 'Farcaster',
    aliases: ['farcaster.xyz', 'Merkle Manufactory', 'Warpcast'],
    tier: 'P2',
    backers: ['a16z', 'Paradigm'],
    sector: 'Social',
    office_location: 'Los Angeles, USA',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Scroll',
    aliases: ['scroll.io'],
    tier: 'P2',
    backers: ['Polychain', 'Bain Capital Crypto'],
    sector: 'Layer 2',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Tools for Humanity',
    aliases: ['worldcoin.org', 'Worldcoin', 'World'],
    tier: 'P2',
    backers: ['a16z', 'Blockchain Capital'],
    sector: 'Identity',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Series C',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Berachain',
    aliases: ['berachain.com'],
    tier: 'P2',
    backers: ['Polychain', 'Hack VC', 'Framework Ventures'],
    sector: 'Layer 1',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Privy',
    aliases: ['privy.io'],
    tier: 'P2',
    backers: ['Paradigm', 'Sequoia'],
    sector: 'Infrastructure / Auth',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Thirdweb',
    aliases: ['thirdweb.com'],
    tier: 'P2',
    backers: ['Haun Ventures', 'Coinbase Ventures'],
    sector: 'Developer Tools',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Pyth Network',
    aliases: ['pyth.network', 'Pyth'],
    tier: 'P2',
    backers: ['Jump Crypto'],
    sector: 'Oracle',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Biconomy',
    aliases: ['biconomy.io'],
    tier: 'P2',
    backers: ['Binance Labs', 'Coinbase Ventures'],
    sector: 'Infrastructure',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Gelato Network',
    aliases: ['gelato.network', 'Gelato'],
    tier: 'P2',
    backers: ['Dragonfly', 'Galaxy Digital'],
    sector: 'Infrastructure / Automation',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Conduit',
    aliases: ['conduit.xyz'],
    tier: 'P2',
    backers: ['Paradigm', 'Haun Ventures'],
    sector: 'Infrastructure / Rollup',
    office_location: 'San Francisco, USA',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Helius',
    aliases: ['helius.dev'],
    tier: 'P2',
    backers: ['Foundation Capital', 'Coinbase Ventures'],
    sector: 'Infrastructure',
    office_location: 'Remote',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Jito Labs',
    aliases: ['jito.network', 'Jito'],
    tier: 'P2',
    backers: ['Multicoin', 'Framework Ventures'],
    sector: 'DeFi / MEV',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Jupiter',
    aliases: ['jup.ag', 'Jupiter Exchange'],
    tier: 'P2',
    backers: [],
    sector: 'DeFi / DEX',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Pendle',
    aliases: ['pendle.finance'],
    tier: 'P2',
    backers: ['Binance Labs'],
    sector: 'DeFi',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Zora',
    aliases: ['zora.co'],
    tier: 'P2',
    backers: ['Paradigm', 'Coinbase Ventures'],
    sector: 'NFT / Social',
    office_location: 'New York, USA',
    hasToken: true,
    stage: 'Series A',
    careerUrl: 'https://boards.greenhouse.io/zora',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Maple Finance',
    aliases: ['maple.finance', 'Maple'],
    tier: 'P2',
    backers: ['Framework Ventures', 'Polychain'],
    sector: 'DeFi / Lending',
    office_location: 'Sydney, Australia',
    hasToken: true,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Aztec',
    aliases: ['aztec.network'],
    tier: 'P2',
    backers: ['a16z', 'Paradigm'],
    sector: 'Privacy / ZK',
    office_location: 'London, UK',
    hasToken: false,
    stage: 'Series B',
    careerUrl: 'https://boards.greenhouse.io/aztec',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'QuickNode',
    aliases: ['quicknode.com'],
    tier: 'P2',
    backers: ['10T Holdings', 'Tiger Global'],
    sector: 'Infrastructure',
    office_location: 'Miami, USA',
    hasToken: false,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Immunefi',
    aliases: ['immunefi.com'],
    tier: 'P2',
    backers: ['Framework Ventures', 'Samsung Next'],
    sector: 'Security',
    office_location: 'Remote',
    hasToken: false,
    stage: 'Series A',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Sky Mavis',
    aliases: ['skymavis.com', 'Axie Infinity', 'Ronin'],
    tier: 'P2',
    backers: ['a16z', 'Paradigm', 'Hashed'],
    sector: 'Gaming',
    office_location: 'Ho Chi Minh City, Vietnam',
    hasToken: true,
    stage: 'Series B',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Wormhole',
    aliases: ['wormhole.com', 'Wormhole Foundation'],
    tier: 'P2',
    backers: ['Jump Crypto', 'Multicoin'],
    sector: 'Cross-chain',
    office_location: 'Remote',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Ankr',
    aliases: ['ankr.com'],
    tier: 'P2',
    backers: ['Binance Labs'],
    sector: 'Infrastructure',
    office_location: 'San Francisco, USA',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
];

/**
 * Find a priority company by name (case-insensitive match on name + aliases)
 */
export function findPriorityCompany(name: string): PriorityCompany | null {
  if (!name) return null;
  const lower = name.toLowerCase().trim();

  for (const company of PRIORITY_COMPANIES) {
    if (company.name.toLowerCase() === lower) {
      return company;
    }
    for (const alias of company.aliases) {
      if (alias.toLowerCase() === lower) {
        return company;
      }
    }
  }
  return null;
}
