/**
 * Priority Companies Registry
 * Korean Web3 companies with VC backing and metadata
 */

export type CareerPlatform = 'lever' | 'greenhouse' | 'ashby' | 'wanted' | 'notion' | null

export interface PriorityCompany {
  name: string;
  aliases: string[];
  tier: 'P0' | 'P1' | 'P2';
  backers: string[];
  sector: string;
  office_location: string;
  hasToken: boolean;
  stage: string;
  careerUrl: string | null;
  careerPlatform: CareerPlatform;
}

export const PRIORITY_COMPANIES: PriorityCompany[] = [
  // ── P0: Top-tier Korean Web3 companies ──
  {
    name: 'Hashed',
    aliases: ['hashed.com', 'Hashed Fund'],
    tier: 'P0',
    backers: ['Hashed'],
    sector: 'VC / Investment',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/hashed',
    careerPlatform: 'lever',
  },
  {
    name: 'DSRV',
    aliases: ['dsrvlabs', 'DSRV Labs'],
    tier: 'P0',
    backers: ['Hashed', 'Kakao Ventures'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: 'https://boards.greenhouse.io/dsrv',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'CryptoQuant',
    aliases: ['cryptoquant.com'],
    tier: 'P0',
    backers: ['Hashed', 'Mirae Asset'],
    sector: 'Analytics / Data',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series B',
    careerUrl: 'https://jobs.lever.co/cryptoquant',
    careerPlatform: 'lever',
  },
  {
    name: 'Klaytn',
    aliases: ['Kaia', 'klaytn.foundation', 'Kaia Foundation'],
    tier: 'P0',
    backers: ['Kakao'],
    sector: 'Layer 1',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://boards.greenhouse.io/kaiafoundation',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Wemade',
    aliases: ['WEMIX', 'wemade.com', 'wemix.com'],
    tier: 'P0',
    backers: ['Wemade'],
    sector: 'Gaming / Metaverse',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Public',
    careerUrl: 'https://www.wanted.co.kr/company/4137',
    careerPlatform: 'wanted',
  },
  {
    name: 'LINE NEXT',
    aliases: ['LINE', 'DOSI', 'Finschia', 'line-next'],
    tier: 'P0',
    backers: ['LINE Corporation'],
    sector: 'Platform / NFT',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://boards.greenhouse.io/linenext',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'Dunamu',
    aliases: ['Upbit', 'dunamu.com', 'upbit.com'],
    tier: 'P0',
    backers: ['Dunamu'],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/79',
    careerPlatform: 'wanted',
  },

  // ── P1: Strong Korean Web3 companies ──
  {
    name: 'Bithumb',
    aliases: ['bithumb.com', 'Bithumb Korea'],
    tier: 'P1',
    backers: [],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/203',
    careerPlatform: 'wanted',
  },
  {
    name: 'Korbit',
    aliases: ['korbit.co.kr'],
    tier: 'P1',
    backers: ['SoftBank', 'Kakao Ventures'],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/1017',
    careerPlatform: 'wanted',
  },
  {
    name: 'Ozys',
    aliases: ['ozys.io', 'KLAYswap', 'Orbit Bridge'],
    tier: 'P1',
    backers: [],
    sector: 'DeFi',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/9498',
    careerPlatform: 'wanted',
  },
  {
    name: 'Planetarium',
    aliases: ['planetariumhq', 'Nine Chronicles', 'planetarium.dev'],
    tier: 'P1',
    backers: ['Hashed', 'Animoca Brands'],
    sector: 'Gaming',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Series A',
    careerUrl: 'https://boards.greenhouse.io/planetarium',
    careerPlatform: 'greenhouse',
  },
  {
    name: 'NFTBank',
    aliases: ['nftbank.ai'],
    tier: 'P1',
    backers: ['Hashed', 'a16z'],
    sector: 'Analytics / NFT',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: 'https://jobs.lever.co/nftbank',
    careerPlatform: 'lever',
  },
  {
    name: 'Lambda256',
    aliases: ['lambda256.io', 'Luniverse'],
    tier: 'P1',
    backers: ['Dunamu'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/8052',
    careerPlatform: 'wanted',
  },
  {
    name: 'Ground X',
    aliases: ['groundx.xyz', 'GroundX'],
    tier: 'P1',
    backers: ['Kakao'],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/5091',
    careerPlatform: 'wanted',
  },
  {
    name: 'ICONLOOP',
    aliases: ['iconloop.com', 'ICON', 'iconloop'],
    tier: 'P1',
    backers: [],
    sector: 'Layer 1',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/5380',
    careerPlatform: 'wanted',
  },
  {
    name: 'Cosmostation',
    aliases: ['cosmostation.io'],
    tier: 'P1',
    backers: ['Hashed'],
    sector: 'Infrastructure / Wallet',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://cosmostation.notion.site/careers',
    careerPlatform: 'notion',
  },
  {
    name: 'Xangle',
    aliases: ['xangle.io'],
    tier: 'P1',
    backers: ['Hashed', 'KB Investment'],
    sector: 'Analytics / Data',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Series A',
    careerUrl: 'https://www.wanted.co.kr/company/5827',
    careerPlatform: 'wanted',
  },
  {
    name: 'DeSpread',
    aliases: ['despread.io'],
    tier: 'P1',
    backers: [],
    sector: 'Consulting / Marketing',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://despread.notion.site/careers',
    careerPlatform: 'notion',
  },
  {
    name: 'ChainPartners',
    aliases: ['chainpartners.co', 'Chain Partners'],
    tier: 'P1',
    backers: [],
    sector: 'VC / Advisory',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Superblock',
    aliases: ['superblock.co'],
    tier: 'P1',
    backers: [],
    sector: 'Infrastructure',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },

  // ── P2: Growing Korean Web3 companies ──
  {
    name: 'Yooldo',
    aliases: ['yooldo.gg'],
    tier: 'P2',
    backers: ['Animoca Brands'],
    sector: 'Gaming',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Seed',
    careerUrl: 'https://yooldo.notion.site/careers',
    careerPlatform: 'notion',
  },
  {
    name: 'Presto Labs',
    aliases: ['presto.com', 'Presto'],
    tier: 'P2',
    backers: [],
    sector: 'Trading / Market Making',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://jobs.lever.co/presto',
    careerPlatform: 'lever',
  },
  {
    name: 'Streami',
    aliases: ['streami.co', 'Gopax parent'],
    tier: 'P2',
    backers: [],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/7854',
    careerPlatform: 'wanted',
  },
  {
    name: 'Crescendo',
    aliases: ['crescendo.finance'],
    tier: 'P2',
    backers: [],
    sector: 'DeFi',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Standard Protocol',
    aliases: ['standardprotocol.org'],
    tier: 'P2',
    backers: [],
    sector: 'DeFi',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Seed',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Somesing',
    aliases: ['somesing.io'],
    tier: 'P2',
    backers: [],
    sector: 'Social / Music',
    office_location: 'Seoul, South Korea',
    hasToken: true,
    stage: 'Established',
    careerUrl: null,
    careerPlatform: null,
  },
  {
    name: 'Sandbox Network',
    aliases: ['sandbox.co.kr', 'Sandbox'],
    tier: 'P2',
    backers: [],
    sector: 'Media / Creator',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/3508',
    careerPlatform: 'wanted',
  },
  {
    name: 'Gopax',
    aliases: ['gopax.co.kr'],
    tier: 'P2',
    backers: ['Binance'],
    sector: 'Exchange',
    office_location: 'Seoul, South Korea',
    hasToken: false,
    stage: 'Established',
    careerUrl: 'https://www.wanted.co.kr/company/7854',
    careerPlatform: 'wanted',
  },
  {
    name: 'Kakao Games',
    aliases: ['BORA', 'kakaogames.com', 'bora.eco'],
    tier: 'P2',
    backers: ['Kakao'],
    sector: 'Gaming / Metaverse',
    office_location: 'Seongnam, South Korea',
    hasToken: true,
    stage: 'Public',
    careerUrl: 'https://www.wanted.co.kr/company/284',
    careerPlatform: 'wanted',
  },
];

/**
 * Find a priority company by name (case-insensitive match on name + aliases)
 */
export function findPriorityCompany(name: string): PriorityCompany | null {
  if (!name) return null;
  const lower = name.toLowerCase().trim();

  for (const company of PRIORITY_COMPANIES) {
    if (company.name.toLowerCase() === lower) {
      return company;
    }
    for (const alias of company.aliases) {
      if (alias.toLowerCase() === lower) {
        return company;
      }
    }
  }
  return null;
}
