import 'dotenv/config'
import { supabase } from '../lib/supabase-script'

interface SeedJob {
  title: string
  company: string
  location: string
  type: string
  category: string
  description?: string
  url: string
  salary?: string
  tags?: string
  source: string
  region: string
  postedDate?: string
  isActive: boolean
}

const jobs: SeedJob[] = [
  // ─── Global / Engineering ─────────────────────────────────────────
  {
    title: 'Senior Solidity Engineer',
    company: 'Uniswap Labs',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Design and implement smart contracts for Uniswap v4 hooks and periphery contracts. Requires 3+ years Solidity experience.',
    url: 'https://web3.career/senior-solidity-engineer-uniswap',
    salary: '$180,000 - $240,000',
    tags: JSON.stringify(['Solidity', 'DeFi', 'Smart Contracts', 'Ethereum']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-15T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Rust Blockchain Developer',
    company: 'Solana Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Build and maintain core validator client software in Rust. Deep systems programming experience required.',
    url: 'https://jobs.solana.com/rust-blockchain-developer',
    salary: '$200,000 - $280,000',
    tags: JSON.stringify(['Rust', 'Solana', 'Blockchain', 'Systems Programming']),
    source: 'jobs.solana.com',
    region: 'Global',
    postedDate: '2025-12-20T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Full Stack Web3 Developer',
    company: 'Coinbase',
    location: 'San Francisco, CA',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Build user-facing products connecting millions of users to the crypto economy. React, Node.js, and blockchain integration.',
    url: 'https://web3.career/full-stack-web3-developer-coinbase',
    salary: '$170,000 - $230,000',
    tags: JSON.stringify(['React', 'Node.js', 'TypeScript', 'Web3']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-18T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Smart Contract Auditor',
    company: 'OpenZeppelin',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Audit smart contracts for security vulnerabilities. Expertise in Solidity, formal verification, and EVM internals.',
    url: 'https://cryptojobslist.com/smart-contract-auditor-openzeppelin',
    salary: '$160,000 - $220,000',
    tags: JSON.stringify(['Security', 'Solidity', 'Auditing', 'EVM']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-22T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Backend Engineer – Indexing',
    company: 'The Graph',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Work on decentralized indexing protocol. Build subgraph tooling and improve query performance at scale.',
    url: 'https://web3.career/backend-engineer-indexing-the-graph',
    salary: '$150,000 - $200,000',
    tags: JSON.stringify(['GraphQL', 'Rust', 'Indexing', 'TypeScript']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-10T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Protocol Engineer',
    company: 'Ethereum Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Contribute to Ethereum core protocol development. Work on consensus layer improvements and EIP implementations.',
    url: 'https://ethereum.foundation/protocol-engineer',
    salary: '$160,000 - $250,000',
    tags: JSON.stringify(['Ethereum', 'Consensus', 'Python', 'Go']),
    source: 'ethereum.foundation',
    region: 'Global',
    postedDate: '2025-12-05T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Move Developer',
    company: 'Sui Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Develop Move smart contracts and tooling for the Sui blockchain ecosystem.',
    url: 'https://jobs.sui.io/move-developer',
    salary: '$140,000 - $200,000',
    tags: JSON.stringify(['Move', 'Sui', 'Smart Contracts', 'Rust']),
    source: 'jobs.sui.io',
    region: 'Global',
    postedDate: '2025-12-12T00:00:00Z',
    isActive: true,
  },
  {
    title: 'DevOps Engineer – Blockchain Infrastructure',
    company: 'Alchemy',
    location: 'New York, NY',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Manage and scale blockchain node infrastructure serving millions of requests per second.',
    url: 'https://web3.career/devops-engineer-alchemy',
    salary: '$160,000 - $210,000',
    tags: JSON.stringify(['DevOps', 'Kubernetes', 'AWS', 'Blockchain Nodes']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-08T00:00:00Z',
    isActive: true,
  },
  {
    title: 'ZK Circuits Engineer',
    company: 'Polygon',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Design and implement zero-knowledge circuits for Polygon zkEVM. Strong math and cryptography background required.',
    url: 'https://cryptojobslist.com/zk-circuits-engineer-polygon',
    salary: '$190,000 - $270,000',
    tags: JSON.stringify(['ZK Proofs', 'Cryptography', 'Rust', 'Circom']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-19T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Frontend Engineer – DeFi Dashboard',
    company: 'Aave',
    location: 'London, UK',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Build and maintain the Aave protocol dashboard. React, TypeScript, ethers.js, and data visualization.',
    url: 'https://web3.career/frontend-engineer-defi-aave',
    salary: '$130,000 - $180,000',
    tags: JSON.stringify(['React', 'TypeScript', 'DeFi', 'ethers.js']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-14T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Mobile Engineer – Crypto Wallet',
    company: 'MetaMask',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Develop features for the MetaMask mobile wallet on iOS and Android. React Native and blockchain integration.',
    url: 'https://remoteok.com/mobile-engineer-metamask',
    salary: '$150,000 - $200,000',
    tags: JSON.stringify(['React Native', 'Mobile', 'Wallet', 'Web3']),
    source: 'remoteok.com',
    region: 'Global',
    postedDate: '2025-12-21T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Data Engineer – On-Chain Analytics',
    company: 'Dune Analytics',
    location: 'Berlin, Germany',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Build data pipelines to index and process blockchain data at scale. SQL, Python, and Spark experience.',
    url: 'https://remote3.co/data-engineer-dune-analytics',
    salary: '$140,000 - $190,000',
    tags: JSON.stringify(['Data Engineering', 'SQL', 'Python', 'Analytics']),
    source: 'remote3.co',
    region: 'Global',
    postedDate: '2025-12-11T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Solana Program Developer',
    company: 'Jupiter',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Build and optimize on-chain programs for the Jupiter DEX aggregator on Solana.',
    url: 'https://jobs.solana.com/solana-program-developer-jupiter',
    salary: '$150,000 - $210,000',
    tags: JSON.stringify(['Solana', 'Rust', 'DeFi', 'DEX']),
    source: 'jobs.solana.com',
    region: 'Global',
    postedDate: '2025-12-17T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Site Reliability Engineer',
    company: 'Binance',
    location: 'Singapore',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Ensure high availability of exchange infrastructure. On-call rotation and incident response.',
    url: 'https://web3.career/sre-binance',
    salary: '$140,000 - $200,000',
    tags: JSON.stringify(['SRE', 'Linux', 'Monitoring', 'High Availability']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-09T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Security Engineer',
    company: 'Chainalysis',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Develop tools to detect and analyze blockchain-based illicit activity. Security and forensics background.',
    url: 'https://cryptojobslist.com/security-engineer-chainalysis',
    salary: '$160,000 - $220,000',
    tags: JSON.stringify(['Security', 'Forensics', 'Python', 'Blockchain']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-13T00:00:00Z',
    isActive: true,
  },
  {
    title: 'TypeScript SDK Engineer',
    company: 'Sui Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Build and maintain TypeScript SDKs for the Sui blockchain. Developer experience focus.',
    url: 'https://jobs.sui.io/typescript-sdk-engineer',
    salary: '$130,000 - $180,000',
    tags: JSON.stringify(['TypeScript', 'SDK', 'Sui', 'Developer Tools']),
    source: 'jobs.sui.io',
    region: 'Global',
    postedDate: '2025-12-16T00:00:00Z',
    isActive: true,
  },
  {
    title: 'QA Engineer – DeFi Protocols',
    company: 'MakerDAO',
    location: 'Remote',
    type: 'Contract',
    category: 'Engineering',
    description: 'Test DeFi protocol integrations and smart contract interactions. Foundry and Hardhat experience.',
    url: 'https://remote3.co/qa-engineer-makerdao',
    tags: JSON.stringify(['QA', 'Testing', 'DeFi', 'Foundry']),
    source: 'remote3.co',
    region: 'Global',
    postedDate: '2025-12-06T00:00:00Z',
    isActive: true,
  },
  // ─── Global / Design ──────────────────────────────────────────────
  {
    title: 'Senior Product Designer',
    company: 'Coinbase',
    location: 'Remote',
    type: 'Full-time',
    category: 'Design',
    description: 'Design intuitive user experiences for crypto trading and DeFi products. Figma, prototyping, and user research.',
    url: 'https://web3.career/senior-product-designer-coinbase',
    salary: '$150,000 - $210,000',
    tags: JSON.stringify(['Figma', 'UX', 'Product Design', 'DeFi']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-20T00:00:00Z',
    isActive: true,
  },
  {
    title: 'UX Researcher – Web3',
    company: 'ConsenSys',
    location: 'Remote',
    type: 'Full-time',
    category: 'Design',
    description: 'Conduct user research to inform the design of MetaMask and other ConsenSys products.',
    url: 'https://remoteok.com/ux-researcher-consensys',
    salary: '$120,000 - $170,000',
    tags: JSON.stringify(['UX Research', 'User Testing', 'Web3', 'Figma']),
    source: 'remoteok.com',
    region: 'Global',
    postedDate: '2025-12-07T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Visual Designer – NFT Marketplace',
    company: 'OpenSea',
    location: 'New York, NY',
    type: 'Full-time',
    category: 'Design',
    description: 'Create visual designs for the leading NFT marketplace. Strong portfolio in digital product design.',
    url: 'https://cryptojobslist.com/visual-designer-opensea',
    salary: '$130,000 - $180,000',
    tags: JSON.stringify(['Visual Design', 'NFT', 'UI', 'Branding']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-03T00:00:00Z',
    isActive: true,
  },
  // ─── Global / Marketing ───────────────────────────────────────────
  {
    title: 'Growth Marketing Manager',
    company: 'Arbitrum Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Marketing',
    description: 'Drive user acquisition and ecosystem growth for the Arbitrum L2 network.',
    url: 'https://web3.career/growth-marketing-arbitrum',
    salary: '$120,000 - $170,000',
    tags: JSON.stringify(['Growth', 'Marketing', 'L2', 'DeFi']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-18T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Content Strategist',
    company: 'Messari',
    location: 'Remote',
    type: 'Full-time',
    category: 'Marketing',
    description: 'Develop content strategy for crypto research and intelligence platform. Strong writing and crypto knowledge.',
    url: 'https://remote3.co/content-strategist-messari',
    salary: '$100,000 - $140,000',
    tags: JSON.stringify(['Content', 'Writing', 'Crypto Research', 'SEO']),
    source: 'remote3.co',
    region: 'Global',
    postedDate: '2025-12-04T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Community Manager',
    company: 'Lido',
    location: 'Remote',
    type: 'Full-time',
    category: 'Marketing',
    description: 'Manage and grow the Lido DAO community across Discord, Twitter, and governance forums.',
    url: 'https://cryptojobslist.com/community-manager-lido',
    salary: '$80,000 - $120,000',
    tags: JSON.stringify(['Community', 'Discord', 'DAO', 'Social Media']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-02T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Developer Relations Engineer',
    company: 'Chainlink',
    location: 'Remote',
    type: 'Full-time',
    category: 'Marketing',
    description: 'Create developer documentation, tutorials, and workshops for Chainlink oracle integrations.',
    url: 'https://remoteok.com/devrel-engineer-chainlink',
    salary: '$130,000 - $180,000',
    tags: JSON.stringify(['DevRel', 'Documentation', 'Solidity', 'Oracles']),
    source: 'remoteok.com',
    region: 'Global',
    postedDate: '2025-12-15T00:00:00Z',
    isActive: true,
  },
  // ─── Global / Product ─────────────────────────────────────────────
  {
    title: 'Product Manager – DeFi',
    company: 'Binance',
    location: 'Dubai, UAE',
    type: 'Full-time',
    category: 'Product',
    description: 'Lead product strategy for DeFi offerings on Binance. Cross-functional collaboration with engineering and design.',
    url: 'https://web3.career/product-manager-defi-binance',
    salary: '$150,000 - $220,000',
    tags: JSON.stringify(['Product Management', 'DeFi', 'Strategy', 'Crypto']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-21T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Technical Product Manager – Wallet',
    company: 'Phantom',
    location: 'Remote',
    type: 'Full-time',
    category: 'Product',
    description: 'Define and drive the product roadmap for the Phantom multi-chain wallet.',
    url: 'https://remote3.co/tpm-wallet-phantom',
    salary: '$140,000 - $200,000',
    tags: JSON.stringify(['Product Management', 'Wallet', 'Multi-chain', 'Mobile']),
    source: 'remote3.co',
    region: 'Global',
    postedDate: '2025-12-10T00:00:00Z',
    isActive: true,
  },
  // ─── Global / Operations ──────────────────────────────────────────
  {
    title: 'Operations Lead – DAO',
    company: 'Gitcoin',
    location: 'Remote',
    type: 'Full-time',
    category: 'Operations',
    description: 'Manage day-to-day operations of Gitcoin DAO including governance, treasury, and contributor coordination.',
    url: 'https://web3.career/operations-lead-gitcoin',
    salary: '$110,000 - $150,000',
    tags: JSON.stringify(['Operations', 'DAO', 'Governance', 'Treasury']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-01T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Compliance Officer',
    company: 'Circle',
    location: 'Boston, MA',
    type: 'Full-time',
    category: 'Operations',
    description: 'Ensure regulatory compliance for USDC operations. AML/KYC expertise and familiarity with global regulations.',
    url: 'https://cryptojobslist.com/compliance-officer-circle',
    salary: '$130,000 - $180,000',
    tags: JSON.stringify(['Compliance', 'AML', 'KYC', 'Regulation']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-08T00:00:00Z',
    isActive: true,
  },
  // ─── Global / Research ────────────────────────────────────────────
  {
    title: 'Cryptography Researcher',
    company: 'Ethereum Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Research',
    description: 'Research and develop novel cryptographic constructions for Ethereum scaling and privacy solutions.',
    url: 'https://ethereum.foundation/cryptography-researcher',
    salary: '$170,000 - $250,000',
    tags: JSON.stringify(['Cryptography', 'Research', 'ZK Proofs', 'Mathematics']),
    source: 'ethereum.foundation',
    region: 'Global',
    postedDate: '2025-12-19T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Tokenomics Researcher',
    company: 'Gauntlet',
    location: 'Remote',
    type: 'Full-time',
    category: 'Research',
    description: 'Model and optimize token economics for DeFi protocols. Quantitative finance or economics background.',
    url: 'https://remote3.co/tokenomics-researcher-gauntlet',
    salary: '$150,000 - $210,000',
    tags: JSON.stringify(['Tokenomics', 'Economics', 'DeFi', 'Modeling']),
    source: 'remote3.co',
    region: 'Global',
    postedDate: '2025-12-14T00:00:00Z',
    isActive: true,
  },
  // ─── Global / Internship & Part-time ──────────────────────────────
  {
    title: 'Blockchain Engineering Intern',
    company: 'Paradigm',
    location: 'San Francisco, CA',
    type: 'Internship',
    category: 'Engineering',
    description: 'Summer internship working on blockchain infrastructure and MEV research tooling.',
    url: 'https://web3.career/blockchain-intern-paradigm',
    tags: JSON.stringify(['Internship', 'Blockchain', 'MEV', 'Research']),
    source: 'web3.career',
    region: 'Global',
    postedDate: '2025-12-22T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Part-time Technical Writer',
    company: 'Chainlink',
    location: 'Remote',
    type: 'Part-time',
    category: 'Marketing',
    description: 'Write and maintain developer documentation for Chainlink products. 20 hours per week.',
    url: 'https://remoteok.com/part-time-technical-writer-chainlink',
    salary: '$60,000 - $80,000',
    tags: JSON.stringify(['Technical Writing', 'Documentation', 'Part-time']),
    source: 'remoteok.com',
    region: 'Global',
    postedDate: '2025-12-11T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Smart Contract Freelancer',
    company: 'Immunefi',
    location: 'Remote',
    type: 'Contract',
    category: 'Engineering',
    description: 'Contract role reviewing and auditing smart contracts for the Immunefi bug bounty platform.',
    url: 'https://cryptojobslist.com/smart-contract-freelancer-immunefi',
    tags: JSON.stringify(['Contract', 'Auditing', 'Solidity', 'Bug Bounty']),
    source: 'cryptojobslist.com',
    region: 'Global',
    postedDate: '2025-12-07T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Ecosystem Fund Analyst',
    company: 'Solana Foundation',
    location: 'Remote',
    type: 'Full-time',
    category: 'Operations',
    description: 'Evaluate grant applications and ecosystem investments for the Solana ecosystem fund.',
    url: 'https://jobs.solana.com/ecosystem-fund-analyst',
    salary: '$100,000 - $150,000',
    tags: JSON.stringify(['Grants', 'Analysis', 'Ecosystem', 'Investment']),
    source: 'jobs.solana.com',
    region: 'Global',
    postedDate: '2025-12-13T00:00:00Z',
    isActive: true,
  },
  // ─── Korea / Engineering ──────────────────────────────────────────
  {
    title: '블록체인 백엔드 개발자',
    company: 'Hashed',
    location: '서울, 강남구',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Web3 스타트업 포트폴리오를 위한 백엔드 시스템 개발. Go, Rust 경험 우대.',
    url: 'https://rocketpunch.com/blockchain-backend-developer-hashed',
    salary: '8,000만원 - 1억 2,000만원',
    tags: JSON.stringify(['Go', 'Rust', 'Backend', 'Blockchain']),
    source: 'rocketpunch.com',
    region: 'Korea',
    postedDate: '2025-12-20T00:00:00Z',
    isActive: true,
  },
  {
    title: '스마트 컨트랙트 개발자',
    company: 'Klaytn Foundation',
    location: '서울, 성수동',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Klaytn 블록체인 기반 스마트 컨트랙트 개발 및 감사. Solidity 3년 이상 경력.',
    url: 'https://web3kr.jobs/smart-contract-developer-klaytn',
    salary: '7,000만원 - 1억원',
    tags: JSON.stringify(['Solidity', 'Klaytn', 'Smart Contracts', 'EVM']),
    source: 'web3kr.jobs',
    region: 'Korea',
    postedDate: '2025-12-18T00:00:00Z',
    isActive: true,
  },
  {
    title: 'DeFi 프로토콜 엔지니어',
    company: 'Ozys',
    location: '서울, 강남구',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Kleva, KLAYswap 등 DeFi 프로토콜 개발. AMM, Lending 프로토콜 경험자.',
    url: 'https://rocketpunch.com/defi-protocol-engineer-ozys',
    salary: '7,500만원 - 1억 1,000만원',
    tags: JSON.stringify(['DeFi', 'AMM', 'Solidity', 'Klaytn']),
    source: 'rocketpunch.com',
    region: 'Korea',
    postedDate: '2025-12-15T00:00:00Z',
    isActive: true,
  },
  {
    title: '프론트엔드 개발자 (Web3)',
    company: 'WEMIX',
    location: '서울, 역삼동',
    type: 'Full-time',
    category: 'Engineering',
    description: 'WEMIX 플랫폼 프론트엔드 개발. React, Next.js, Web3.js 경험 필수.',
    url: 'https://jobkorea.co.kr/frontend-developer-wemix',
    salary: '6,000만원 - 9,000만원',
    tags: JSON.stringify(['React', 'Next.js', 'Web3.js', 'Frontend']),
    source: 'jobkorea.co.kr',
    region: 'Korea',
    postedDate: '2025-12-12T00:00:00Z',
    isActive: true,
  },
  {
    title: '블록체인 풀스택 개발자',
    company: 'Lambda256',
    location: '서울, 서초구',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Luniverse 블록체인 플랫폼 풀스택 개발. Node.js, React, AWS 경험 필요.',
    url: 'https://web3kr.jobs/fullstack-developer-lambda256',
    salary: '6,500만원 - 9,500만원',
    tags: JSON.stringify(['Node.js', 'React', 'AWS', 'Blockchain']),
    source: 'web3kr.jobs',
    region: 'Korea',
    postedDate: '2025-12-10T00:00:00Z',
    isActive: true,
  },
  {
    title: 'NFT 마켓플레이스 개발자',
    company: 'Naver Z (ZEP)',
    location: '성남, 분당구',
    type: 'Full-time',
    category: 'Engineering',
    description: '메타버스 기반 NFT 마켓플레이스 백엔드 개발. Java/Kotlin, Spring Boot.',
    url: 'https://rocketpunch.com/nft-marketplace-developer-naverz',
    salary: '6,000만원 - 8,500만원',
    tags: JSON.stringify(['Java', 'Kotlin', 'NFT', 'Spring Boot']),
    source: 'rocketpunch.com',
    region: 'Korea',
    postedDate: '2025-12-08T00:00:00Z',
    isActive: true,
  },
  {
    title: '보안 엔지니어 (블록체인)',
    company: 'S2W',
    location: '판교, 경기도',
    type: 'Full-time',
    category: 'Engineering',
    description: '블록체인 보안 감사 및 온체인 위협 탐지. 스마트 컨트랙트 보안 분석 경험.',
    url: 'https://jobkorea.co.kr/security-engineer-s2w',
    salary: '7,000만원 - 1억원',
    tags: JSON.stringify(['Security', 'Smart Contracts', 'Auditing', 'Blockchain']),
    source: 'jobkorea.co.kr',
    region: 'Korea',
    postedDate: '2025-12-06T00:00:00Z',
    isActive: true,
  },
  {
    title: '블록체인 인프라 엔지니어',
    company: 'Ground X',
    location: '서울, 서초구',
    type: 'Full-time',
    category: 'Engineering',
    description: 'Klaytn 노드 인프라 운영 및 최적화. Linux, Docker, Kubernetes 경험.',
    url: 'https://web3kr.jobs/infra-engineer-groundx',
    salary: '7,000만원 - 1억원',
    tags: JSON.stringify(['Infrastructure', 'Kubernetes', 'Docker', 'Klaytn']),
    source: 'web3kr.jobs',
    region: 'Korea',
    postedDate: '2025-12-04T00:00:00Z',
    isActive: true,
  },
  // ─── Korea / Design ───────────────────────────────────────────────
  {
    title: 'UI/UX 디자이너 (Web3)',
    company: 'Kakao Games (BORA)',
    location: '성남, 분당구',
    type: 'Full-time',
    category: 'Design',
    description: 'BORA 블록체인 게임 플랫폼 UI/UX 디자인. 게임 및 Web3 경험 우대.',
    url: 'https://jobkorea.co.kr/uiux-designer-kakaogames',
    salary: '5,500만원 - 8,000만원',
    tags: JSON.stringify(['UI/UX', 'Figma', 'Game Design', 'Web3']),
    source: 'jobkorea.co.kr',
    region: 'Korea',
    postedDate: '2025-12-16T00:00:00Z',
    isActive: true,
  },
  {
    title: '프로덕트 디자이너',
    company: 'Upbit (Dunamu)',
    location: '서울, 서초구',
    type: 'Full-time',
    category: 'Design',
    description: 'Upbit 거래소 프로덕트 디자인. 사용자 리서치, 프로토타이핑, 디자인 시스템 구축.',
    url: 'https://rocketpunch.com/product-designer-upbit',
    salary: '6,000만원 - 9,000만원',
    tags: JSON.stringify(['Product Design', 'Figma', 'UX Research', 'Design Systems']),
    source: 'rocketpunch.com',
    region: 'Korea',
    postedDate: '2025-12-14T00:00:00Z',
    isActive: true,
  },
  // ─── Korea / Marketing ────────────────────────────────────────────
  {
    title: '마케팅 매니저 (Web3)',
    company: 'Hashed',
    location: '서울, 강남구',
    type: 'Full-time',
    category: 'Marketing',
    description: 'Web3 생태계 마케팅 전략 수립 및 실행. 커뮤니티 관리 및 파트너십.',
    url: 'https://web3kr.jobs/marketing-manager-hashed',
    salary: '5,500만원 - 8,000만원',
    tags: JSON.stringify(['Marketing', 'Community', 'Partnership', 'Web3']),
    source: 'web3kr.jobs',
    region: 'Korea',
    postedDate: '2025-12-19T00:00:00Z',
    isActive: true,
  },
  {
    title: '콘텐츠 크리에이터',
    company: 'Xangle',
    location: '서울, 강남구',
    type: 'Full-time',
    category: 'Marketing',
    description: '크립토 리서치 콘텐츠 제작. 블록체인 기술 이해 및 글쓰기 역량 필수.',
    url: 'https://rocketpunch.com/content-creator-xangle',
    salary: '4,500만원 - 6,500만원',
    tags: JSON.stringify(['Content', 'Research', 'Writing', 'Crypto']),
    source: 'rocketpunch.com',
    region: 'Korea',
    postedDate: '2025-12-11T00:00:00Z',
    isActive: true,
  },
  // ─── Korea / Product ──────────────────────────────────────────────
  {
    title: '프로덕트 매니저 (블록체인)',
    company: 'LINE NEXT',
    location: '서울, 강남구',
    type: 'Full-time',
    category: 'Product',
    description: 'LINE 블록체인 기반 제품 기획. 글로벌 NFT 플랫폼 DOSI 서비스 관리.',
    url: 'https://jobkorea.co.kr/product-manager-linenext',
    salary: '7,000만원 - 1억원',
    tags: JSON.stringify(['Product Management', 'NFT', 'Blockchain', 'Global']),
    source: 'jobkorea.co.kr',
    region: 'Korea',
    postedDate: '2025-12-17T00:00:00Z',
    isActive: true,
  },
  // ─── Korea / Operations ───────────────────────────────────────────
  {
    title: '사업 개발 매니저 (BD)',
    company: 'Klaytn Foundation',
    location: '서울, 성수동',
    type: 'Full-time',
    category: 'Operations',
    description: 'Klaytn 생태계 파트너십 및 사업 개발. 글로벌 프로젝트 온보딩.',
    url: 'https://web3kr.jobs/bd-manager-klaytn',
    salary: '6,000만원 - 9,000만원',
    tags: JSON.stringify(['Business Development', 'Partnership', 'Ecosystem']),
    source: 'web3kr.jobs',
    region: 'Korea',
    postedDate: '2025-12-09T00:00:00Z',
    isActive: true,
  },
  // ─── Korea / Research ─────────────────────────────────────────────
  {
    title: '블록체인 리서처',
    company: 'Decipher (서울대)',
    location: '서울, 관악구',
    type: 'Part-time',
    category: 'Research',
    description: '블록체인 기술 연구 및 논문 작성. 컨센서스, ZK, MEV 관련 리서치.',
    url: 'https://web3kr.jobs/blockchain-researcher-decipher',
    tags: JSON.stringify(['Research', 'ZK', 'Consensus', 'Academic']),
    source: 'web3kr.jobs',
    region: 'Korea',
    postedDate: '2025-12-22T00:00:00Z',
    isActive: true,
  },
  {
    title: 'Web3 데이터 분석가',
    company: 'CryptoQuant',
    location: '서울, 강남구',
    type: 'Full-time',
    category: 'Research',
    description: '온체인 데이터 분석 및 인사이트 리포트 작성. SQL, Python, 블록체인 데이터 경험.',
    url: 'https://jobkorea.co.kr/data-analyst-cryptoquant',
    salary: '5,500만원 - 8,500만원',
    tags: JSON.stringify(['Data Analysis', 'On-chain', 'SQL', 'Python']),
    source: 'jobkorea.co.kr',
    region: 'Korea',
    postedDate: '2025-12-21T00:00:00Z',
    isActive: true,
  },
]

async function seedJobs() {
  console.log(`Seeding ${jobs.length} jobs into Supabase...`)

  const { data, error } = await supabase
    .from('Job')
    .upsert(jobs, { onConflict: 'url' })
    .select()

  if (error) {
    console.error('Failed to seed jobs:', error.message)
    process.exit(1)
  }

  console.log(`Successfully upserted ${data.length} jobs.`)

  // Summary breakdown
  const regions: Record<string, number> = {}
  const categories: Record<string, number> = {}
  const sources: Record<string, number> = {}
  const types: Record<string, number> = {}

  for (const job of jobs) {
    regions[job.region] = (regions[job.region] || 0) + 1
    categories[job.category] = (categories[job.category] || 0) + 1
    sources[job.source] = (sources[job.source] || 0) + 1
    types[job.type] = (types[job.type] || 0) + 1
  }

  console.log('\n--- Breakdown ---')
  console.log('Regions:', regions)
  console.log('Categories:', categories)
  console.log('Sources:', sources)
  console.log('Types:', types)
}

seedJobs()
